# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_guide',
                'doc_host': 'https://ayushmandloi2.github.io',
                'git_url': 'https://github.com/ayushmandloi2/nbdev_guide',
                'lib_path': 'nbdev_guide'},
  'syms': {'nbdev_guide.core': {'nbdev_guide.core.foo': ('core.html#foo', 'nbdev_guide/core.py')}}}
